apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cravat-templates-trio
spec:
  templates:
    - name: cravat-trio-template
      inputs:
        parameters:
          - name: proband-vcf
          - name: mother-vcf
          - name: father-vcf
          - name: ref-version
          - name: annotators
          - name: modules-dir
            default: "/opt/open-cravat/cravat/modules"
          - name: output-dir
      volumes:
        - name: proband-vcf
          hostPath:
            path: "{{inputs.parameters.proband-vcf}}"
            type: File
        - name: mother-vcf
          hostPath:
            path: "{{inputs.parameters.mother-vcf}}"
            type: File
        - name: father-vcf
          hostPath:
            path: "{{inputs.parameters.father-vcf}}"
            type: File
        - name: modules-dir
          hostPath:
            path: "{{inputs.parameters.modules-dir}}"
            type: Directory
        - name: output-dir
          hostPath:
            path: "{{inputs.parameters.output-dir}}"
            type: DirectoryOrCreate
      script:
        name: cravat-trio
        image: bergun/gennext-cravat:0.2.11c-alpha-no_mu
        command: [sh]
        source: |
          oc run \
          "/mnt/input/{{=sprig.osBase(inputs.parameters['father-vcf'])}}" \
          "/mnt/input/{{=sprig.osBase(inputs.parameters['mother-vcf'])}}" \
          "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}" \
          -a {{inputs.parameters.annotators}} \
          -l {{inputs.parameters.ref-version}} \
          --skip reporter \
          --temp-files \
          --cleanrun \
          -d "{{inputs.parameters.output-dir}}"
        volumeMounts:
          - name: proband-vcf
            mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}"
          - name: mother-vcf
            mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['mother-vcf'])}}"
          - name: father-vcf
            mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['father-vcf'])}}"
          - name: modules-dir
            mountPath: "/opt/"
          - name: output-dir
            mountPath: "/mnt/output/"
    - name: cravat-trio-template-nodeSelector
      nodeSelector:
        kubernetes.io/hostname: "{{inputs.parameters.node-name}}"
      inputs:
        parameters:
          - name: proband-vcf
          - name: mother-vcf
          - name: father-vcf
          - name: ref-version
          - name: annotators
          - name: modules-dir
            default: "/opt/open-cravat/cravat/modules"
          - name: output-dir
          - name: node-name
      volumes:
        - name: proband-vcf
          hostPath:
            path: "{{inputs.parameters.proband-vcf}}"
            type: File
        - name: mother-vcf
          hostPath:
            path: "{{inputs.parameters.mother-vcf}}"
            type: File
        - name: father-vcf
          hostPath:
            path: "{{inputs.parameters.father-vcf}}"
            type: File
        - name: modules-dir
          hostPath:
            path: "{{inputs.parameters.modules-dir}}"
            type: Directory
        - name: output-dir
          hostPath:
            path: "{{inputs.parameters.output-dir}}"
            type: DirectoryOrCreate
      script:
        name: cravat-trio
        image: bergun/gennext-cravat:0.2.0-alpha
        command: [sh]
        source: |
          oc run \
          "/mnt/input/{{=sprig.osBase(inputs.parameters['father-vcf'])}}" \
          "/mnt/input/{{=sprig.osBase(inputs.parameters['mother-vcf'])}}" \
          "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}" \
          -a {{inputs.parameters.annotators}} \
          -l {{inputs.parameters.ref-version}} \
          --skip reporter \
          --temp-files \
          --cleanrun \
          -d "{{inputs.parameters.output-dir}}"
        volumeMounts:
          - name: proband-vcf
            mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}"
          - name: mother-vcf
            mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['mother-vcf'])}}"
          - name: father-vcf
            mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['father-vcf'])}}"
          - name: modules-dir
            mountPath: "/opt/"
          - name: output-dir
            mountPath: "/mnt/output/"
